name: Daily Property Data Workflow

on:
  schedule:
    # Runs at 8:00 AM UTC every day
    - cron: "0 8 * * *"
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "Creating .env file with secrets..."
          echo "ATTOM_API_KEY=${{ secrets.ATTOM_API_KEY }}" > .env
          echo "RENTCAST_API_KEY=${{ secrets.RENTCAST_API_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

      - name: Run ATTOM daily tasks
        run: |
          echo "Running ATTOM daily tasks at $(date)"
          npm run daily-task

      - name: Wait for database to process ATTOM data
        run: |
          echo "Waiting 5 minutes before running RentCast tasks..."
          sleep 300

      - name: Run RentCast daily tasks
        run: |
          echo "Running RentCast daily tasks at $(date)"
          npm run rentcast-daily-task

      - name: Run property linking tasks
        run: |
          echo "Running property linking tasks at $(date)"
          npm run link-properties

      - name: Report status
        run: |
          echo "Daily workflow completed successfully"
          echo "ATTOM, RentCast, and property linking tasks completed at $(date)"
